### ISSUE TITLE
Testing with binary-charts > 7.30.0 breaks the production.

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-charts#142]
Here's the situation:

I use npm install to install the packages before deploying to the production server. If the last installed version of binary-charts was <= 7.30.0 it works without any problem. But assume that I installed binary-charts@latest (without saving to the package.json) for testing. If I forget to install binary-charts@7.30.0 before deploy the deployed version will be the latest, because npm install actually assumes that a satisfying version is already there and there's no need to downgrade! Which is not the case because the changes in binary-charts > 7.30.0 where breaking changes, though this is not reflected in the versioning.
A quick fix is to use fixed version 7.30.0 in the package.json, but this is not a good practice.
So would you please issue a major release everytime your changes were breaking changes, and if by accident you published a breaking change, would you please deprecate the old package and issue a major release?
I mean could you please follow [SemVer convention](http://semver.org).

Thanks in advance.

**Comment by qingweibinary** [comment]
Guess boris did it kind of involuntarily, and yes @borisyankov we'd better do it more formally if we want people to use it =)

**Comment by borisyankov** [comment]
Yeah, in retrospect, we should have done a 8.0.0-alpha.1 or something.

**Comment by aminmarashi** [comment]
Then I think this should be closed.
