### ISSUE TITLE
Use close values instead of ticks for time intervals more than one tick

### ISSUE THREAD

**Issue by aminmarashi** [binary-com/binary-charts#172]
Currently we use the tick stream to draw the line/area chart. This works fine until we switch to another time interval (e.g. 1min). Other projects such as webtrader use `close` values to draw the line/area chart in this case.
I'll try to fix this and make a PR.

**Comment by borisyankov** [comment]
Cool. Makes sense.

**Comment by aminmarashi** [comment]
@borisyankov I'm going to remove dataGrouping, from the chart with this feature.
I suggest we request for 1000 entries (for each interval) like what the webtrader does and let the users change the resolution with the time interval.
This requires the users to implement getData method correctly.
Another possible solution is to use liveapi to get the tick data separately from the users code, what do you think?

**Comment by aminmarashi** [comment]
PR: #175
